CREATE TABLE analysis (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Compatível com H2 e Postgres
    date_created TIMESTAMP,
    analyzed_text TEXT,
    forecast VARCHAR(255),
    probability FLOAT
);